# -----------------------------------------------------------------------------
# This stage builds the development image
# -----------------------------------------------------------------------------
# Note we need a version of Node that is supported by ember-cli.
# See: https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md
#
FROM node:14-alpine as development

# Install Ember CLI
# "unsafe-perm" step is a workaround for a bug.
# See: https://github.com/npm/uid-number/issues/7
RUN npm config set unsafe-perm true && npm install --global ember-cli && ember --version \
    && npm install --global eslint && eslint --version;

RUN apt-get update; \
    apt -y --no-install-recommends install git; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

WORKDIR "/application/web"
RUN npm install